spring.application.name=security-service

# DataBase
spring.profiles.active=env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.enabled=false


# Spring Security Oauth API's
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

### microservices setup ###
server.port=${server_port}
eureka.client.service-url.defaultZone=${eureka_server_url}


# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRY}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRY}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


### log's ###
##################################################
# Logging Configuration
##################################################

logging.file.name=logs/security-microservice.log

logging.level.root=INFO

logging.level.com.security.microservice=DEBUG